# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
repos:
  CRAN: https://cloud.r-project.org
  alteryx: https://alteryx.github.io/drat
